import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Nav from '../../src/components/web/nav/Nav'
import Recent from '../../src/components/web/recent/Recent'
import NewsLetter from '../../src/components/web/newsLetter/NewsLetter'
import Footer from '../../src/components/web/footer/Footer'
import CartC from '../../src/components/web/cart/Cart'
import { getCart, updateCartAdd, updateCartRemove, removeFromCart, clearError, clearMessage } from '../../src/redux/features/cartSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useCallback } from 'react'
import Toast from '../../src/components/toast/Toast'

const Cart: NextPage = () => {
    const dispatch = useAppDispatch()

    const { token } = useAppSelector((state) => state.auth)

    const { success: cartSuccess, message: cartMessage, error: cartError, loading: cartLoading, loadingUpdateCart, cartItems, loadingFetchCart } = useAppSelector(state => state.cart)

    // fetch cart items
    const fetchCart = useCallback(() => {
        dispatch(getCart(token))
    }, [dispatch, token])

    useEffect(() => {
        fetchCart()
    }, [fetchCart])

    // clear error and success message after 3 seconds
    useEffect(() => {
        if (cartError) {
            setTimeout(() => {
                dispatch(clearError())
            }, 3000);
        }
    }, [cartError, dispatch])

    useEffect(() => {
        if (cartSuccess) {
            setTimeout(() => {
                dispatch(clearMessage())
                dispatch(getCart(token))
            }, 1000);
        }
    }, [cartSuccess, dispatch, token])

    // update cart add
    const handleUpdateCart = useCallback((data: any) => {
        dispatch(updateCartAdd(data));
    }, [dispatch]);

    // update cart remove
    const handleUpdateCartRemove = useCallback((data: any) => {
        dispatch(updateCartRemove(data));
    }, [dispatch]);

    // remove from cart
    const handleRemoveFromCart = useCallback((id: number) => {
        dispatch(removeFromCart(id));
    }, [dispatch]);


    return (
        <div>
            <Head>
                <title>Flip</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/flip-favicon.png" />
            </Head>

            <Nav />

            <div className='relative'>
                {cartSuccess && <Toast message={cartMessage} bgColor='green' />}
                {cartError && <Toast message={cartError} bgColor='red' />}
            </div>


            <section className="bg-white w-full h-full">

                <div className='container mx-auto px-4 md:px-10'>

                    <CartC
                        cartItems={cartItems}
                        cartLoading={cartLoading}
                        removeFromCart={handleRemoveFromCart}
                        updateCartAdd={handleUpdateCart}
                        loadingUpdateCart={loadingUpdateCart}
                        updateCartRemove={handleUpdateCartRemove}
                        loadingFetchCart={loadingFetchCart}
                    />

                    <Recent />


                    <NewsLetter />

                    <div className="pt-20"></div>


                </div>

            </section>

            <footer className="bg-backg w-full h-full">
                <Footer />
            </footer>

        </div>
    )
}

export default Cart