import React, { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import "react-multi-carousel/lib/styles.css";
import Nav from '../../src/components/web/nav/Nav'
import Recent from '../../src/components/web/recent/Recent'
import NewsLetter from '../../src/components/web/newsLetter/NewsLetter'
import Footer from '../../src/components/web/footer/Footer'
import SearchProductComponent from '../../src/components/web/product/SearchProduct';
import { useRouter } from "next/router";
import { getAllProducts, getProductsCategory } from '../../src/redux/features/productSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useCallback } from 'react'
import { addToCart, getCart, updateCartAdd, updateCartRemove, clearError, clearMessage } from '../../src/redux/features/cartSlice'
import Toast from '../../src/components/toast/Toast'

const SearchProduct: NextPage = () => {
    const { query } = useRouter() as any
    const dispatch = useAppDispatch()

    const [search, setSearch] = useState(typeof window !== 'undefined' && query.search || '')
    const [category, setCategory] = useState(typeof window !== 'undefined' && query.category || '')
    const [priceRange, setPriceRange] = useState(typeof window !== 'undefined' && query.priceRange || '')
    const [discountPercentage, setDiscountPercentage] = useState(typeof window !== 'undefined' && query.discountPercentage || '')
    const [freeDelivery, setFreeDelivery] = useState(typeof window !== 'undefined' && query.freeDelivery || '')
    const [byMerchant, setByMerchant] = useState(typeof window !== 'undefined' && query.byMerchant || '')

    const { token } = useAppSelector((state) => state.auth)

    const { loading, products, productsCategory, loadingFetchProducts } = useAppSelector((state) => state.product)
    const { success: cartSuccess, message: cartMessage, error: cartError, loading: cartLoading, cartItems, loadingUpdateCart } = useAppSelector(state => state.cart)

    // set search, category, priceRange, discountPercentage, freeDelivery, byMerchant from query
    useEffect(() => {
        if (typeof window !== 'undefined') {
            if (query) {
                setSearch(query.search || '')
                setCategory(query.category || '')
                setPriceRange(query.priceRange || '')
                setDiscountPercentage(query.discountPercentage || '')
                setFreeDelivery(query.freeDelivery || '')
                setByMerchant(query.byMerchant || '')
            } else {
                setSearch('')
                setCategory('')
                setPriceRange('')
                setDiscountPercentage('')
                setFreeDelivery('')
                setByMerchant('')
            }
        }
    }, [query])

    // fetch products and category
    const fetchProductsAndCategory = useCallback(() => {
        if (typeof window !== 'undefined' && query && query.search) {
            dispatch(getAllProducts({ search, category, priceRange, discountPercentage, freeDelivery, byMerchant }))
            dispatch(getProductsCategory(token))
        }
    }, [dispatch, token, query, search, category, priceRange, discountPercentage, freeDelivery, byMerchant])

    useEffect(() => {
        fetchProductsAndCategory()
    }, [fetchProductsAndCategory])

    // clear error and success message after 3 seconds
    useEffect(() => {
        if (cartError) {
            setTimeout(() => {
                dispatch(clearError())
            }, 3000);
        }
    }, [cartError, dispatch])

    useEffect(() => {
        if (cartSuccess) {
            setTimeout(() => {
                dispatch(clearMessage())
                dispatch(getCart(token))
            }, 1000);
        }
    }, [cartSuccess, dispatch, token])

    // add to cart
    const handleAddToCart = useCallback((data: any) => {
        dispatch(addToCart(data))
    }, [dispatch])

    // update cart add
    const handleUpdateCart = useCallback((data: any) => {
        dispatch(updateCartAdd(data))
    }, [dispatch])

    // update cart remove
    const handleUpdateCartRemove = useCallback((data: any) => {
        dispatch(updateCartRemove(data))
    }, [dispatch])

    return (
        <div>
            <Head>
                <title>Flip</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/flip-favicon.png" />
            </Head>

            <Nav />

            <div className='relative'>
                {cartSuccess && <Toast message={cartMessage} bgColor='green' />}
                {cartError && <Toast message={cartError} bgColor='red' />}
            </div>

            <section className="bg-white w-full h-full">

                <div className='container mx-auto px-4 md:px-10'>


                    <SearchProductComponent
                        loading={loading}
                        filteredProducts={products}
                        query={query}
                        loadingFetchProducts={loadingFetchProducts}
                        productsCategory={productsCategory}

                        addToCart={handleAddToCart}
                        cartLoading={cartLoading}
                        updateCartRemove={handleUpdateCartRemove}
                        updateCartAdd={handleUpdateCart}
                        loadingUpdateCart={loadingUpdateCart}
                        cartItems={cartItems}
                    />

                    <Recent />


                    <NewsLetter />

                    <div className="pt-20"></div>


                </div>

            </section>

            <footer className="bg-backg w-full h-full">
                <Footer />
            </footer>

        </div>
    )
}

export default SearchProduct