import React from 'react'
import Layout from '../../src/components/dashboard/admin-layout/AdminLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Message from '../../src/components/dashboard/inbox/Message'
import { getAllChats, getSingleChat, sendMesage, clearMessage, clearError } from '../../src/redux/features/messageSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect } from 'react'
import AlertModal from '../../src/components/alert/Alert'

const Inbox: NextPage = () => {
    const dispatch = useAppDispatch()

    const { loading, error, success, message, allChats, singleChat, loadingFetchAllChats, loadingFetchSingleChat } = useAppSelector((state) => state.message)

    useEffect(() => {
        dispatch(getAllChats(''))
        dispatch(getSingleChat(2))
    }, [dispatch])

    useEffect(() => {
        if (success) {
            dispatch(getAllChats(''))
            dispatch(getSingleChat(3))
            dispatch(clearMessage())
        }
    }, [error, success, dispatch])

    const handleSendMessage = (data: any) => {
        dispatch(sendMesage(data))
    }

    return (
        <div>
            <Layout title="Inbox">
                <Head>
                    <title>Cue |  The artisan for Digital and Offline Space</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/flip-favicon.png" />
                </Head>

                <Message
                    allChats={allChats}
                    singleChat={singleChat}
                    loadingFetchAllChats={loadingFetchAllChats}
                    loadingFetchSingleChat={loadingFetchSingleChat}
                    sendMesage={handleSendMessage}
                />

                {error &&
                    <AlertModal
                        title='Error'
                        message={error}
                        confirmButtonText="Ok"
                        type="error"
                        onConfirm={() => {
                            dispatch(clearError())
                            dispatch(getAllChats(''))
                        }}
                    />
                }

                <footer >

                </footer>
            </Layout>
        </div>
    )
}

export default Inbox