import React from 'react'
import Layout from '../../src/components/dashboard/admin-layout/AdminLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import Message from '../../src/components/dashboard/inbox/Message'
import { getAllChats, getSingleChat, sendMesage, clearMessageChat, clearErrorChat } from '../../src/redux/features/messageSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useCallback } from 'react'
import AlertModal from '../../src/components/alert/Alert'

const Inbox: NextPage = () => {
    const dispatch = useAppDispatch()

    const { error, success, allChats, singleChat, loadingFetchAllChats, loadingFetchSingleChat } = useAppSelector((state) => state.message)

    // fetch all chats
    const fetchAllChats = useCallback(() => {
        dispatch(getAllChats(''))
        // dispatch(getSingleChat(2))
    }, [dispatch])

    useEffect(() => {
        fetchAllChats()
    }, [fetchAllChats])

    useEffect(() => {
        if (success) {
            dispatch(getAllChats(''))
            // dispatch(getSingleChat(3))
            dispatch(clearMessageChat())
        }
    }, [success, dispatch])

    // send message
    const handleSendMessage = useCallback((data: any) => {
        dispatch(sendMesage(data))
    }, [dispatch])

    return (
        <div>
            <Layout title="Inbox">
                <Head>
                    <title>Flip</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/flip-favicon.png" />
                </Head>

                <Message
                    allChats={allChats}
                    singleChat={singleChat}
                    loadingFetchAllChats={loadingFetchAllChats}
                    loadingFetchSingleChat={loadingFetchSingleChat}
                    sendMesage={handleSendMessage}
                />

                {error &&
                    <AlertModal
                        title='Error'
                        message={error}
                        confirmButtonText="Ok"
                        type="error"
                        onConfirm={() => {
                            dispatch(clearErrorChat())
                            dispatch(getAllChats(''))
                        }}
                    />
                }

                <footer >

                </footer>
            </Layout>
        </div>
    )
}

export default Inbox