import type { NextPage } from 'next'
import Head from 'next/head'
import "react-multi-carousel/lib/styles.css";
import Nav from '../src/components/web/nav/Nav'
import Banner from '../src/components/web/banners/Banner'
import Quality from '../src/components/web/quality/Quality'
import FlashSales from '../src/components/web/flashSales/FlashSales'
import Banner2 from '../src/components/web/banners/Banner2'
import Services from '../src/components/web/service/Services'
import Featured from '../src/components/web/featured/Featured'
import TopCategories from '../src/components/web/category/TopCategories'
import NewsLetter from '../src/components/web/newsLetter/NewsLetter'
import Footer from '../src/components/web/footer/Footer'

import { getProductsCategory, getAllProducts } from '../src/redux/features/productSlice'
import { getServicesCategory, } from '../src/redux/features/serviceSlice'
import { useAppSelector, useAppDispatch } from '../src/redux/hooks'
import { useEffect } from 'react'

const Home: NextPage = () => {
  const dispatch = useAppDispatch()

  const { token } = useAppSelector((state) => state.auth)

  const { loading, productsCategory, products } = useAppSelector((state) => state.product)
  const { loading: loadingFetchServices, servicesCategories } = useAppSelector((state) => state.service)

  useEffect(() => {
    dispatch(getProductsCategory(token))
    dispatch(getServicesCategory(token))
    dispatch(getAllProducts(token))
  }, [dispatch, token])

  return (
    <>
      {loading || loadingFetchServices || productsCategory.length === 0 || products.length === 0 ? (
        <div className="flex justify-center items-center h-screen">
          <div className="animate-spin rounded-full h-20 w-20 border-t-2 border-b-2 border-primary3"></div>
        </div>
      ) : (
        <div>
          <Head>
            <title>Cue |  The artisan for Digital and Offline Space</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/flip-favicon.png" />
          </Head>

          <Nav />


          <section className="bg-white w-full h-full">

            <div className='container mx-auto px-4 md:px-10'>

              <Banner
                productsCategory={productsCategory}
                products={products}
              />

              <Quality />

              <FlashSales
                products={products}
              />

              <Banner2 />

              <Services
                services={servicesCategories}
              />

              <Featured
                products={products}
              />

              <TopCategories
                productsCategory={productsCategory}
              />

              <NewsLetter />

              <div className="pt-20"></div>


            </div>

          </section>

          <footer className="bg-backg w-full h-full">
            <Footer />
          </footer>

        </div>
      )}

    </>
  )
}

export default Home
