import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import "react-multi-carousel/lib/styles.css";
import Nav from '../src/components/web/nav/Nav'
import ServiceComponent from '../src/components/web/service/ServiceCategory'
import Recent from '../src/components/web/recent/Recent'
import NewsLetter from '../src/components/web/newsLetter/NewsLetter'
import Footer from '../src/components/web/footer/Footer'
import { getAllServices, getServicesCategory } from '../src/redux/features/serviceSlice'
import { useAppSelector, useAppDispatch } from '../src/redux/hooks'
import { useEffect } from 'react'

const Service: NextPage = () => {
    const dispatch = useAppDispatch()

    const { token } = useAppSelector((state) => state.auth)

    const { loading: loadingServices, error: errorServices, success: successServices, services, servicesCategories } = useAppSelector((state) => state.service)

    useEffect(() => {
        dispatch(getAllServices(token))
        dispatch(getServicesCategory(token))
    }, [dispatch, token])


    return (
        <div>
            <Head>
                <title>Cue |  The artisan for Digital and Offline Space</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/flip-favicon.png" />
            </Head>

            <Nav />

            <section className="bg-white w-full h-full">

                <div className='container mx-auto px-4 md:px-10'>

                    <ServiceComponent
                        services={services}
                        servicesCategories={servicesCategories}
                    />

                    <Recent />


                    <NewsLetter />

                    <div className="pt-20"></div>


                </div>

            </section>

            <footer className="bg-backg w-full h-full">
                <Footer />
            </footer>

        </div>
    )
}

export default Service