import React from 'react'
import Layout from '../../src/components/dashboard/admin-layout/AdminLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
const Settings: NextPage = () => {
  return (
    <div>
      <Layout title="Settings">
        <Head>
          <title>Flip</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/flip-favicon.png" />
        </Head>

        <h1>Settings Page</h1>

        <footer >

        </footer>
      </Layout>
    </div>
  )
}

export default Settings