import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import "react-multi-carousel/lib/styles.css";
import Nav from '../../src/components/web/nav/Nav'
import Recent from '../../src/components/web/recent/Recent'
import NewsLetter from '../../src/components/web/newsLetter/NewsLetter'
import Footer from '../../src/components/web/footer/Footer'
import SearchServiceComponent from '../../src/components/web/service/SearchService';
import { useRouter } from "next/router";
import { getAllServices, getServicesCategory } from '../../src/redux/features/serviceSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useState } from 'react'

const SearchService: NextPage = () => {
    const { query } = useRouter() as any
    const dispatch = useAppDispatch()
    const [filteredService, setfFilteredService] = useState([] as any)

    const { token } = useAppSelector((state) => state.auth)

    const { loadingFetchServices, services, servicesCategories } = useAppSelector((state) => state.service)

    useEffect(() => {
        dispatch(getAllServices(token))
        dispatch(getServicesCategory(token))
    }, [dispatch, token])

    useEffect(() => {
        if (services.length > 0 && query.search) {
            setfFilteredService(services.filter((item: any) => {
                return item.category.name.toLowerCase().includes(query.search.toLowerCase()) ||
                    item.service.location.toLowerCase().includes(query.search.toLowerCase()) ||
                    item.service.serviceName.toLowerCase().includes(query.search.toLowerCase())
            }))
        } else {
            setfFilteredService([] as any)
        }
    }, [services, query])
    return (
        <div>
            <Head>
                <title>Cue |  The artisan for Digital and Offline Space</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/flip-favicon.png" />
            </Head>

            <Nav />

            <section className="bg-white w-full h-full">

                <div className='container mx-auto px-4 md:px-10'>

                    <SearchServiceComponent
                        loadingFetchServices={loadingFetchServices}
                        services={filteredService}
                        query={query}
                        servicesCategories={servicesCategories}
                    />

                    <Recent />


                    <NewsLetter />

                    <div className="pt-20"></div>


                </div>

            </section>

            <footer className="bg-backg w-full h-full">
                <Footer />
            </footer>

        </div>
    )
}

export default SearchService