import React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import "react-multi-carousel/lib/styles.css";
import Nav from '../../src/components/web/nav/Nav'
import Recent from '../../src/components/web/recent/Recent'
import NewsLetter from '../../src/components/web/newsLetter/NewsLetter'
import Footer from '../../src/components/web/footer/Footer'
import SearchServiceComponent from '../../src/components/web/service/SearchService';
import { useRouter } from "next/router";
import { getAllServices, getServicesCategory } from '../../src/redux/features/serviceSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useState, useCallback } from 'react'

const SearchService: NextPage = () => {
    const { query } = useRouter() as any
    const dispatch = useAppDispatch()

    const [search, setSearch] = useState(typeof window !== 'undefined' && query.search || '')
    const [category, setCategory] = useState(typeof window !== 'undefined' && query.category || '')
    const [state, setState] = useState(typeof window !== 'undefined' && query.state || '')
    const [lga, setLga] = useState(typeof window !== 'undefined' && query.lga || '')
    const [byMerchant, setByMerchant] = useState(typeof window !== 'undefined' && query.byMerchant || '')

    const { token } = useAppSelector((state) => state.auth)

    const { loadingFetchServices, services, servicesCategories } = useAppSelector((state) => state.service)

    useEffect(() => {
        if (typeof window !== 'undefined') {
            if (query) {
                setSearch(query.search || '')
                setState(query.state || '')
                setLga(query.lga || '')
                setCategory(query.category || '')
                setByMerchant(query.byMerchant || '')
            } else {
                setSearch('')
                setState('')
                setLga('')
                setCategory('')
                setByMerchant('')
            }
        }
    }, [query])

    const fetchServiceAndCategory = useCallback(() => {
        if (typeof window !== 'undefined' && query && query.search) {
            dispatch(getAllServices({ search, category, state, lga, byMerchant }))
            dispatch(getServicesCategory(token))
        }
    }, [dispatch, query, token, search, category, state, lga, byMerchant])

    useEffect(() => {
        fetchServiceAndCategory()
    }, [fetchServiceAndCategory])
    

    return (
        <div>
            <Head>
                <title>Flip</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/flip-favicon.png" />
            </Head>

            <Nav />

            <section className="bg-white w-full h-full">

                <div className='container mx-auto px-4 md:px-10'>

                    <SearchServiceComponent
                        loadingFetchServices={loadingFetchServices}
                        services={services}
                        query={query}
                        servicesCategories={servicesCategories}
                    />

                    <Recent />


                    <NewsLetter />

                    <div className="pt-20"></div>


                </div>

            </section>

            <footer className="bg-backg w-full h-full">
                <Footer />
            </footer>

        </div>
    )
}

export default SearchService