import React from 'react'
import Layout from '../../src/components/dashboard/admin-layout/AdminLayout'
import type { NextPage } from 'next'
import Head from 'next/head'
import JobsComponent from '../../src/components/dashboard/job/Jobs'
import { getAllJobs, clearError, clearMessage } from '../../src/redux/features/jobSlice'
import { createProposal, clearProposalError, clearProposalMessage } from '../../src/redux/features/proposalSlice'
import { useAppSelector, useAppDispatch } from '../../src/redux/hooks'
import { useEffect, useCallback } from 'react'
import AlertModal from '../../src/components/alert/Alert'


const Jobs: NextPage = () => {
    const dispatch = useAppDispatch()
    const { token } = useAppSelector((state) => state.auth)
    const { jobs, success, error, message, loading, loadingFetchJobs, successFetchJobs } = useAppSelector(state => state.job)
    const { success: successProposal, error: errorProposal, message: messageProposal, loading: loadingProposal } = useAppSelector(state => state.proposal)

    // fetch jobs
    const fetchJobs = useCallback(() => {
        dispatch(getAllJobs(token))
    }, [dispatch, token])

    useEffect(() => {
        fetchJobs()
    }, [fetchJobs])
    
    // create proposal
    const handleCreateProposal = useCallback((data: any) => {
        dispatch(createProposal(data))
    }, [dispatch])

    return (
        <div>
            <Layout title="Gigs">
                <Head>
                    <title>Flip</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/flip-favicon.png" />
                </Head>

                <JobsComponent
                    jobs={jobs}
                    loadingFetchJobs={loadingFetchJobs}
                    createProposal={handleCreateProposal}
                    successProposal={successProposal}
                    loadingProposal={loadingProposal}
                />


                {error &&
                    <AlertModal
                        title='Error'
                        message={error}
                        confirmButtonText="Ok"
                        type="error"
                        onConfirm={() => {
                            dispatch(clearError())
                        }}
                    />
                }

                {success &&
                    <AlertModal
                        title='Success'
                        message={message}
                        confirmButtonText="Ok"
                        type="success"
                        onConfirm={() => {
                            dispatch(clearMessage())
                        }}
                    />
                }


                {errorProposal &&
                    <AlertModal
                        title='Error'
                        message={errorProposal}
                        confirmButtonText="Ok"
                        type="error"
                        onConfirm={() => {
                            dispatch(clearProposalError())
                        }}
                    />
                }

                {successProposal &&
                    <AlertModal
                        title='Success'
                        message={messageProposal}
                        confirmButtonText="Ok"
                        type="success"
                        onConfirm={() => {
                            dispatch(clearProposalMessage())
                            dispatch(getAllJobs(token))
                        }}
                    />
                }


                <footer >

                </footer>
            </Layout>
        </div>
    )
}

export default Jobs